# Generated by Django 3.0.5 on 2020-04-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretbored', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='savedScales',
        ),
        migrations.AddField(
            model_name='user',
            name='savedScales',
            field=models.ManyToManyField(null=True, related_name='users', to='fretbored.SavedScale'),
        ),
    ]
