# Generated by Django 3.0.5 on 2020-04-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fretbored', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savedScales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='fretbored.Scale'),
            preserve_default=False,
        ),
    ]
