# Generated by Django 3.0.5 on 2020-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretbored', '0002_auto_20200423_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedscale',
            name='key',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedscale',
            name='key_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedscale',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
