# Generated by Django 3.0.5 on 2020-04-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fretbored', '0002_user_savedscales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='savedScales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='fretbored.Scale'),
        ),
    ]
